# Generated by Django 5.2.5 on 2025-11-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['anio', 'division', 'apellido', 'nombre']},
        ),
    ]
