# Generated by Django 5.2.5 on 2025-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='anio',
            field=models.CharField(choices=[('primero', '1ro'), ('segundo', '2do'), ('tercero', '3ro'), ('cuarto', '4to'), ('quinto', '5to'), ('sexto', '6to')], max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='division',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=1),
        ),
    ]
